{
  PrivilegedExceptionAction<VisibilityLabelsResponse> action=new PrivilegedExceptionAction<VisibilityLabelsResponse>(){
    public VisibilityLabelsResponse run() throws Exception {
      String[] labels={"L1",SECRET,"L2","invalid~","L3"};
      VisibilityLabelsResponse response=null;
      try {
        response=VisibilityClient.addLabels(conf,labels);
      }
 catch (      Throwable e) {
        fail("Should not have thrown exception");
      }
      List<RegionActionResult> resultList=response.getResultList();
      assertEquals(5,resultList.size());
      assertTrue(resultList.get(0).getException().getValue().isEmpty());
      assertEquals("org.apache.hadoop.hbase.DoNotRetryIOException",resultList.get(1).getException().getName());
      assertTrue(Bytes.toString(resultList.get(1).getException().getValue().toByteArray()).contains("org.apache.hadoop.hbase.security.visibility.LabelAlreadyExistsException: " + "Label 'secret' already exists"));
      assertTrue(resultList.get(2).getException().getValue().isEmpty());
      assertTrue(resultList.get(3).getException().getValue().isEmpty());
      assertTrue(resultList.get(4).getException().getValue().isEmpty());
      return null;
    }
  }
;
  SUPERUSER.runAs(action);
}
