{
  this.exception=new IOException(reason);
  if (this.failureCb.get() != null) {
    this.failureCb.get().run(this.exception);
  }
}
