{
  try {
    master.isSnapshotDone(null,snapshot);
    Assert.fail("didn't fail to lookup a snapshot");
  }
 catch (  ServiceException se) {
    try {
      throw ProtobufUtil.getRemoteException(se);
    }
 catch (    HBaseSnapshotException e) {
      assertEquals("Threw wrong snapshot exception!",clazz,e.getClass());
    }
catch (    Throwable t) {
      Assert.fail("Threw an unexpected exception:" + t);
    }
  }
}
