{
  try {
    context.done(get(get));
  }
 catch (  Throwable e) {
    context.error(e);
  }
}
