{
  try {
    action.perform();
  }
 catch (  Exception ex) {
    LOG.warn("Exception occurred during performing action: " + StringUtils.stringifyException(ex));
  }
}
