{
  ForeignExceptionMessage exception=result.getForeignExceptionMessage();
  String msg=exception != null ? result.getExceptionFullMessage() : "no exception found";
  assertFalse(msg,result.isFailed());
}
