{
  try {
    return getWAL(null);
  }
 catch (  IOException e) {
    LOG.warn("getWAL threw exception " + e);
    return null;
  }
}
