{
  if (canRetry && throwable != null && throwable instanceof DoNotRetryIOException) {
    canRetry=false;
  }
  if (canRetry && callback != null) {
    canRetry=callback.retriableFailure(originalIndex,row,throwable);
  }
  if (!canRetry) {
    if (callback != null) {
      callback.failure(originalIndex,row,throwable);
    }
    errors.add(throwable,row,server);
    this.hasError.set(true);
  }
  return canRetry;
}
