{
  if (workers == null || workers.isEmpty())   return;
  for (  Worker worker : workers) {
    Exception e=worker.getSavedException();
    if (e != null) {
      LOG.error("Found exception in thread: " + worker.getName());
      e.printStackTrace();
    }
    Assert.assertNull("Action failed: " + worker.getAction() + " in thread: "+ worker.getName(),e);
  }
}
